Review one of your past projects
DianaBeki/landingpage pull request #1
Opened 2022-10-31 15:33 UTC by DianaBeki

In the following task, I did the following
- Added index.html file
- Added style.css

2022-10-31 19:43 UTC, DianaBeki reviewed
Hi @DianaBeki  
Good job so far! 
👏👏👏 
There are some issues that you still need to work on to go to the next project but you're almost there!

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## To Highlight 🎉

- Good Pr Description✔️ 
- Meaningful commits ✔️


_**Notes To Consider For Your Next Projects**_

- Good Job so far, your commit message is clear and meaningful but kindly make sure in your next projects, The commit message should be committed separately for each file.



 ## Required Changes ♻️


- [x] 🛑 You should use a linter to check on errors before pushing your project.
- [x] 🛑 update readme file with correct LinkedIn issues URL, Add MIT template.




## Optional suggestions

- N/A

**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-31 19:43 UTC, DianaBeki commented on css/style.css
> +}
- Check your linter errors to avoid syntax errors and make your code readable and smartly organized.

2022-10-31 20:00 UTC, bienvenuushindi requested changes
### Hi @Rana-Mudassir ,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Highlights) Good Points: :+1:
- Inline comments are present. ✔

## (Changes Required) Aspects to improve: ♻️
- [ ] **For more changes  Please check the inline comments below.**
## [Optional] suggestions:
N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-11-01 20:08 UTC, PinkMoon25 approved these changes
Hi @DianaBeki , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
Good Pr Description :heavy_check_mark:
Meaningful commits :heavy_check_mark:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

[OPTIONAL] As suggested by the previous reviewer, https://github.com/DianaBeki/landingpage/pull/1#discussion_r1009806620 please always make sure to provide details to the student so it is clear hoe can he improve or what changes he have to make specifically, a good rule of thumb :+1: is "Always try to be helpful"

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-01 20:14 UTC, merged